import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Menu";


export const metadata: Metadata = {
  title: "Origamid next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body>
        <NavBar />
        {children}
        
        </body>
    </html>
  );
}
